# Generated by Django 4.2.2 on 2023-07-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('total_spend', models.FloatField()),
                ('total_income', models.FloatField()),
                ('total_savings', models.FloatField()),
                ('total_saved_this_period', models.FloatField()),
                ('start_balance', models.FloatField()),
                ('end_balance', models.FloatField()),
            ],
        ),
    ]
