# Generated by Django 4.2.2 on 2023-08-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_rename_category_id_expense_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="planned_amount",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="planned_amount",
            field=models.FloatField(null=True),
        ),
    ]
