# Generated by Django 4.2.2 on 2023-08-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_remove_monthlyperiod_end_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="description",
        ),
        migrations.RemoveField(
            model_name="income",
            name="description",
        ),
        migrations.AlterField(
            model_name="expense",
            name="actual_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="expense",
            name="planned_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="income",
            name="actual_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="income",
            name="planned_amount",
            field=models.FloatField(default=0),
        ),
    ]
