# Generated by Django 4.2.2 on 2023-08-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_rename_actual_amount_expense_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyperiod",
            name="categories",
            field=models.ManyToManyField(
                related_name="monthly_categories", to="finance.category"
            ),
        ),
    ]
