# Generated by Django 4.2.2 on 2023-08-30 11:24

from django.db import migrations, models


def create_initial_currencies(apps, scheme_editor):
    Currency = apps.get_model("finance", "Currency")
    Currency.objects.create(title="Pound Sterling", label="pound", symbol="£", rate=1, code="GBP")
    Currency.objects.create(title="Euro", label="euro", symbol="€", rate=1.1, code="EUR")
    Currency.objects.create(title="US Dollar", label="dollar", symbol="$", rate=1.3, code="USD")


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_alter_monthlyperiod_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=50)),
                ("rate", models.FloatField(default=1)),
                ("code", models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(create_initial_currencies),
    ]
