# Generated by Django 4.2.2 on 2023-07-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20230708_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='expenses',
            field=models.ManyToManyField(related_name='period_expense_set', to='finance.expense'),
        ),
        migrations.AddField(
            model_name='period',
            name='incomes',
            field=models.ManyToManyField(related_name='period_incomes_set', to='finance.income'),
        ),
    ]
