# Generated by Django 4.2.2 on 2023-08-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_expense_description_remove_income_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
